export const GET_ATENDEE = 'APP/ATTENDEE/GET_ATENDEE';
export const GET_ATENDEE_SUCCESS = 'APP/ATTENDEE/GET_ATENDEE_SUCCESS';
export const GET_ATENDEE_FAILED = 'APP/ATTENDEE/GET_ATENDEE_FAILED';

export const GET_ATENDEE_COUNT = 'APP/ATTENDEE/GET_ATENDEE_COUNT';
export const GET_ATENDEE_COUNT_SUCCESS =
  'APP/ATTENDEE/GET_ATENDEE_COUNT_SUCCESS';
export const GET_ATENDEE_COUNT_FAILED = 'APP/ATTENDEE/GET_ATENDEE_COUNT_FAILED';

export const ADD_ATTENDEE = 'APP/ATTENDEE/ADD_ATTENDEE';
export const ADD_ATTENDEE_SUCCESS = 'APP/ATTENDEE/ADD_ATTENDEE_SUCCESS';
export const ADD_ATTENDEE_FAILED = 'APP/ATTENDEE/ADD_ATTENDEE_FAILED';
