export const GET_WEBINAR_ATTENDEES = 'APP/WEBINARS/GET_WEBINAR_ATTENDEES';
export const SET_WEBINAR_ATTENDEES = 'APP/WEBINARS/SET_WEBINAR_ATTENDEES';
export const GET_ATTENDEE_DETAILS = 'APP/WEBINARS/GET_ATTENDEE_DETAILS';
export const SET_ATTENDEE_DETAILS = 'APP/WEBINARS/SET_ATTENDEE_DETAILS';
