export const FORGOT_PASSWORD = 'APP/FORGOT-PASSWORD/FORGOT_PASSWORD';
export const RESET_PASSWORD = 'APP/FORGOT-PASSWORD/RESET_PASSWORD';
export const SET_PASSWORD = 'APP/FORGOT-PASSWORD/SET_PASSWORD';
