export const PAYMENTS_COUNT = 'APP/PAYMENTS/PAYMENTS_COUNT';
export const PAYMENTS_GET = 'APP/PAYMENTS/PAYMENTS_GET';
export const PAYMENTS_FAILED = 'APP/PAYMENTS/PAYMENTS_FAILED';
export const PAYMENTS_SUCCESS = 'APP/PAYMENTS/PAYMENTS_SUCCESS';