export const PLANS_COUNT = 'APP/PLANS/PLANS_COUNT';
export const PLANS_GET = 'APP/PLANS/PLANS_GET';
export const PLANS_FAILED = 'APP/PLANS/PLANS_FAILED';
export const PLANS_SUCCESS = 'APP/PLANS/PLANS_SUCCESS';
