export const LOAD_ERRORS = 'APP/GLOBAL/LOAD_ERRORS';
export const CLEAR_ERRORS = 'APP/GLOBAL/CLEAR_ERRORS';
export const LOADING = 'APP/GLOBAL/LOADING';
export const LOAD_SUCCESS = 'APP/GLOBAL/LOAD_SUCCESS';