// REDUX ACTION TYPES
export const TICK = 'APP/COUNTER/TICK';
export const INCREMENT = 'APP/COUNTER/INCREMENT';
export const DECREMENT = 'APP/COUNTER/DECREMENT';
export const RESET = 'APP/COUNTER/RESET';