export const GET_WEBINAR_LIST = 'APP/WEBINARS/GET_WEBINAR_LIST';
export const SET_WEBINAR_LIST = 'APP/WEBINARS/SET_WEBINAR_LIST';
export const CREATE_WEBINAR = 'APP/WEBINARS/CREATE_WEBINAR';
export const WEBINAR_DETAILS = 'APP/WEBINARS/WEBINAR_DETAILS';
export const SET_WEBINAR = 'APP/WEBINARS/SET_WEBINAR';