export const GET_BANK_LIST = 'APP/WALLET/GET_BANK_LIST';
export const SET_BANK_LIST = 'APP/WALLET/SET_BANK_LIST';
export const ADD_BANK = 'APP/WALLET/ADD_BANK';
export const SET_BANK = 'APP/WALLET/SET_BANK';
export const UPDATE_BANK = 'APP/WALLET/UPDATE_BANK';
export const REMOVE_BANK = 'APP/WALLET/REMOVE_BANK';
