export const GET_SIGNUP = 'APP/SIGNUP/GET_SIGNUP';
export const GET_SIGNUP_SUCCESS = 'APP/SIGNUP/GET_SIGNUP_SUCCESS';
export const GET_SIGNUP_FAILED = 'APP/SIGNUP/GET_SIGUP_FAILED';

export const POST_SIGNUP = 'APP/SIGNUP/POST_SIGNUP';
export const POST_SIGNUP_SUCCESS = 'APP/SIGNUP/POST_SIGNUP_SUCCESS';
export const POST_SIGNUP_FAILED = 'APP/SIGNUP/POST_SIGUP_FAILED';