export const GET_ZOOM_ACCOUNT = 'APP/ACCOUNTS/GET_ZOOM_ACCOUNT';
export const GET_ZOOM_ACCOUNT_SUCCESS = 'APP/ACCOUNTS/GET_ZOOM_ACCOUNT_SUCCESS';
export const GET_ZOOM_ACCOUNT_FAILED = 'APP/ACCOUNTS/GET_ZOOM_ACCOUNT_FAILED';