export const GET_ZOOM_ACCOUNT = 'APP/ACCOUNTS/GET_ZOOM_ACCOUNT';
export const SUBMIT_ZOOM_CODE = 'APP/ACCOUNTS/SUBMIT_ZOOM_CODE';
export const SET_ZOOM_ACCOUNT = 'APP/ACCOUNTS/SET_ZOOM_ACCOUNT';
export const SET_ZOOM_ACCOUNT_LIST = 'APP/ACCOUNTS/SET_ZOOM_ACCOUNT_LIST';
export const CREATE_ZOOM_ACCOUNT = 'APP/ACCOUNTS/CREATE_ZOOM_ACCOUNT';
export const ZOOM_SUBSCRIPTION = 'APP/ACCOUNTS/ZOOM_SUBSCRIPTION';
export const CAPTURE_PURCHASE = 'APP/ACCOUNTS/CAPTURE_PURCHASE';
