export const GET_TRANSACTION = 'APP/WALLET/GET_TRANSACTION';
export const SET_TRANSACTION = 'APP/WALLET/SET_TRANSACTION';
export const GET_TRANSACTION_DETAILS = 'APP/WALLET/GET_TRANSACTION_DETAILS';
export const SET_TRANSACTION_DETAILS = 'APP/WALLET/SET_TRANSACTION_DETAILS';
